### ISSUE TITLE
bug(nodejs): owlbot post-processor fails to compile protos

### ISSUE THREAD

**Issue by chingor13** [googleapis/synthtool#1374]
```
Already have image (with digest): gcr.io/cloud-devrel-public-resources/owlbot-nodejs:latest@sha256:8730ec2b4f2a998e81626bcb2acf001f5148ef5d2e1ab7de38c3055444dc0bee
+ '[' -f owlbot.py ']'
+ python owlbot.py
2022-03-17 16:34:18,455 synthtool [CRITICAL] > You are running the synthesis script directly, this will be disabled in a future release of Synthtool. Please use python3 -m synthtool instead.
2022-03-17 16:34:18,702 synthtool [INFO] > Collected versions $['github', 'utils', 'bin'] from $src
INFO:synthtool:Collected versions $['github', 'utils', 'bin'] from $src
2022-03-17 16:34:18,702 synthtool [DEBUG] > Using local templates at /synthtool/synthtool/gcp/templates
DEBUG:synthtool:Using local templates at /synthtool/synthtool/gcp/templates
2022-03-17 16:34:18,722 synthtool [INFO] > successfully generate `src/index.ts`
INFO:synthtool:successfully generate `src/index.ts`
2022-03-17 16:34:18,831 synthtool [DEBUG] > Post-processing GAPIC library...
DEBUG:synthtool:Post-processing GAPIC library...
2022-03-17 16:34:18,831 synthtool [DEBUG] > Copy eslint config
DEBUG:synthtool:Copy eslint config
2022-03-17 16:34:19,247 synthtool [DEBUG] > Running fix...
DEBUG:synthtool:Running fix...
version: 15
2022-03-17 16:34:25,231 synthtool [DEBUG] > Compiling protos...
DEBUG:synthtool:Compiling protos...
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, open 'protos/protos.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'protos/protos.json'
}
2022-03-17 16:34:25,383 synthtool [ERROR] > Failed executing /synthtool/node_modules/.bin/compileProtos src:

None
ERROR:synthtool:Failed executing /synthtool/node_modules/.bin/compileProtos src:

None
Skipping: .eslintignore
.eslintrc.json
.gitattributes
Skipping: .github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md
.github/auto-approve.yml
.github/generated-files-bot.yml
Skipping: .github/release-please.yml
.github/release-trigger.yml
.github/workflows/ci.yaml
.kokoro/.gitattributes
.kokoro/common.cfg
.kokoro/continuous/node10/common.cfg
.kokoro/continuous/node10/docs.cfg
.kokoro/continuous/node10/test.cfg
.kokoro/continuous/node12/common.cfg
.kokoro/continuous/node12/lint.cfg
.kokoro/continuous/node12/samples-test.cfg
.kokoro/continuous/node12/system-test.cfg
.kokoro/continuous/node12/test.cfg
.kokoro/docs.sh
.kokoro/lint.sh
.kokoro/populate-secrets.sh
.kokoro/presubmit/node10/common.cfg
.kokoro/presubmit/node12/common.cfg
.kokoro/presubmit/node12/samples-test.cfg
.kokoro/presubmit/node12/system-test.cfg
.kokoro/presubmit/node12/test.cfg
.kokoro/publish.sh
.kokoro/release/docs-devsite.cfg
.kokoro/release/docs-devsite.sh
.kokoro/release/docs.cfg
.kokoro/release/docs.sh
.kokoro/release/publish.cfg
.kokoro/samples-test.sh
.kokoro/system-test.sh
.kokoro/test.bat
.kokoro/test.sh
.kokoro/trampoline.sh
.kokoro/trampoline_v2.sh
.mocharc.js
.nycrc
Skipping: .prettierignore
.prettierrc.js
.trampolinerc
CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE
Skipping: README.md
SECURITY.md
Skipping: renovate.json
Skipping: samples/README.md
Traceback (most recent call last):
  File "/workspace/code-suggester/owlbot.py", line 17, in <module>
    node.owlbot_main(templates_excludes=[
  File "/synthtool/synthtool/languages/node.py", line 338, in owlbot_main
    postprocess_gapic_library_hermetic()
  File "/synthtool/synthtool/languages/node.py", line 242, in postprocess_gapic_library_hermetic
    compile_protos_hermetic(hide_output=hide_output)
  File "/synthtool/synthtool/languages/node.py", line 224, in compile_protos_hermetic
    shell.run(
  File "/synthtool/synthtool/shell.py", line 39, in run
    raise exc
  File "/synthtool/synthtool/shell.py", line 27, in run
    return subprocess.run(
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/synthtool/node_modules/.bin/compileProtos', 'src']' returned non-zero exit status 1.
```

**Comment by chingor13** [comment]
This is on the googleapis/code-suggester repo which does not have protos
