### ISSUE TITLE
[Java] OwlBot PostProcessor fails to work with java-grafeas module

### ISSUE THREAD

**Issue by suztomo** [googleapis/synthtool#1743]
On https://github.com/googleapis/google-cloud-java/pull/8956, OwlBot PostProcessor fails to work with java-grafeas module. It failed:

```
Traceback (most recent call last):
 File "/owlbot/src/fix-poms.py", line 504, in <module>
   main()
 File "/owlbot/src/fix-poms.py", line 472, in main
   update_parent_pom("pom.xml", modules)
 File "/owlbot/src/fix-poms.py", line 174, in update_parent_pom
   m.text for i, m in enumerate(existing) if m.text not in module_names
TypeError: 'NoneType' object is not iterable
```

https://pantheon.corp.google.com/cloud-build/builds;region=global/0cf25338-9826-4fda-abcf-dfa5592b5223;step=5?project=repo-automation-bots

I will work on fixing it.

CC: @JoeWang1127 

# How to reproduce issue locally

```
cd google-cloud-java; git fetch
git checkout -b java-grafeas_postprocessor origin/main 
mkdir -p owl-bot-staging/java-grafeas
docker run --rm --user "$(id -u):$(id -g)"         -v "$(pwd):/workspace"   -w /workspace         --env HOME=/tmp         gcr.io/cloud-devrel-public-resources/owlbot-java
```

**Comment by suztomo** [comment]
Why java-grafeas was touched by the pull request https://github.com/googleapis/google-cloud-java/pull/8956?
