### ISSUE TITLE
ModuleNotFoundError: No module named 'google.protobuf'

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/synthtool#304]
I followed the instructions in README.md, and got this error:
```ps1
**********************
Windows PowerShell transcript start
Start time: 20191010153505
Username: GOOGLE\rennie
RunAs User: GOOGLE\rennie
Configuration Name: 
Machine: RENNIE1-W (Microsoft Windows NT 10.0.16299.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 9204
PSVersion: 5.1.16299.1146
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.16299.1146
BuildVersion: 10.0.16299.1146
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is ~\synthtool.log
PS C:\Users\rennie> python3
python3 : The term 'python3' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ python3
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (python3:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
python3 : The term 'python3' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ python3
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (python3:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\rennie> python
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z
PS C:\Users\rennie> $env:PATH="C:\Users\rennie\AppData\Local\Programs\Python\Python37;$env:PATH"
PS C:\Users\rennie> python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z
PS C:\Users\rennie> python3 -m pip install --user --upgrade gcp-synthtool
python3 : The term 'python3' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ python3 -m pip install --user --upgrade gcp-synthtool
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (python3:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
python3 : The term 'python3' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ python3 -m pip install --user --upgrade gcp-synthtool
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (python3:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\rennie> python -m pip install --user --upgrade gcp-synthtool
Collecting gcp-synthtool
  Downloading https://files.pythonhosted.org/packages/c6/da/9cfae56fa1beccadfd24bf2e7bd95d16ca29c372a671bb540e66b3925872/gcp_synthtool-2019.5.2-py3-
none-any.whl (76kB)
    100% |████████████████████████████████| 81kB 2.2MB/s
Collecting requests (from gcp-synthtool)
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-non
e-any.whl (57kB)
    100% |████████████████████████████████| 61kB 2.2MB/s
Requirement not upgraded as not directly required: jinja2 in c:\users\rennie\appdata\local\programs\python\python37\lib\site-packages (from gcp-synt
htool) (2.10)
Collecting packaging (from gcp-synthtool)
  Downloading https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none
-any.whl
Collecting protobuf (from gcp-synthtool)
  Downloading https://files.pythonhosted.org/packages/a8/ae/a11b9b0c8e2410b11887881990b71f54ec39b17c4de2b5d850ef66aade8c/protobuf-3.10.0-cp37-cp37m-
win_amd64.whl (1.0MB)
    100% |████████████████████████████████| 1.0MB 3.4MB/s
Collecting PyYAML (from gcp-synthtool)
  Downloading https://files.pythonhosted.org/packages/bc/3f/4f733cd0b1b675f34beb290d465a65e0f06b492c00b111d1b75125062de1/PyYAML-5.1.2-cp37-cp37m-win
_amd64.whl (215kB)
    100% |████████████████████████████████| 225kB 3.2MB/s
Requirement not upgraded as not directly required: click in c:\users\rennie\appdata\local\programs\python\python37\lib\site-packages (from gcp-synth
tool) (7.0)
Collecting colorlog (from gcp-synthtool)
  Downloading https://files.pythonhosted.org/packages/68/4d/892728b0c14547224f0ac40884e722a3d00cb54e7a146aea0b3186806c9e/colorlog-4.0.2-py2.py3-none
-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->gcp-synthtool)
  Downloading https://files.pythonhosted.org/packages/e0/da/55f51ea951e1b7c63a579c09dd7db825bb730ec1fe9c0180fc77bfb31448/urllib3-1.25.6-py2.py3-none
-any.whl (125kB)
    100% |████████████████████████████████| 133kB 3.7MB/s
Collecting idna<2.9,>=2.5 (from requests->gcp-synthtool)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.w
hl (58kB)
    100% |████████████████████████████████| 61kB 2.4MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests->gcp-synthtool)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-
any.whl (133kB)
    100% |████████████████████████████████| 143kB 3.0MB/s
Collecting certifi>=2017.4.17 (from requests->gcp-synthtool)
  Downloading https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-n
one-any.whl (154kB)
    100% |████████████████████████████████| 163kB 3.1MB/s
Requirement not upgraded as not directly required: MarkupSafe>=0.23 in c:\users\rennie\appdata\local\programs\python\python37\lib\site-packages (fro
m jinja2->gcp-synthtool) (1.1.0)
Collecting pyparsing>=2.0.2 (from packaging->gcp-synthtool)
  Downloading https://files.pythonhosted.org/packages/11/fa/0160cd525c62d7abd076a070ff02b2b94de589f1a9789774f17d7c54058e/pyparsing-2.4.2-py2.py3-non
e-any.whl (65kB)
    100% |████████████████████████████████| 71kB 2.3MB/s
Collecting six (from packaging->gcp-synthtool)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any
.whl
Requirement not upgraded as not directly required: setuptools in c:\users\rennie\appdata\local\programs\python\python37\lib\site-packages (from prot
obuf->gcp-synthtool) (39.0.1)
Collecting colorama; sys_platform == "win32" (from colorlog->gcp-synthtool)
  Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none
-any.whl
Installing collected packages: urllib3, idna, chardet, certifi, requests, pyparsing, six, packaging, protobuf, PyYAML, colorama, colorlog, gcp-synth
tool
  The script chardetect.exe is installed in 'C:\Users\rennie\AppData\Roaming\Python\Python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script synthtool.exe is installed in 'C:\Users\rennie\AppData\Roaming\Python\Python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed PyYAML-5.1.2 certifi-2019.9.11 chardet-3.0.4 colorama-0.4.1 colorlog-4.0.2 gcp-synthtool-2019.5.2 idna-2.8 packaging-19.2 pro
tobuf-3.10.0 pyparsing-2.4.2 requests-2.22.0 six-1.12.0 urllib3-1.25.6
You are using pip version 10.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\Users\rennie> $env:PATH="C:\Users\rennie\AppData\Roaming\Python\Python37\Scripts;$env:PATH"
PS C:\Users\rennie> cd gitrepos
PS C:\Users\rennie\gitrepos> cd google-cloud-python
cd : Cannot find path 'C:\Users\rennie\gitrepos\google-cloud-python' because it does not exist.
At line:1 char:1
+ cd google-cloud-python
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\rennie...le-cloud-python:String) [Set-Location], 
ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
cd : Cannot find path 'C:\Users\rennie\gitrepos\google-cloud-python' because it does not exist.
At line:1 char:1
+ cd google-cloud-python
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\rennie...le-cloud-python:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\Users\rennie\gitrepos> git clone git@github.com:googleapis/google-cloud-python.git
Cloning into 'google-cloud-python'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 1756163 (delta 7), reused 9 (delta 1), pack-reused 1756128Receiving objects: 100% (1756163/1756163), 1.69 GiB | 2.98 MiB/s
Receiving objects: 100% (1756163/1756163), 1.69 GiB | 2.86 MiB/s, done.
Resolving deltas: 100% (1330108/1330108), done.
Checking out files: 100% (4211/4211), done.
PS C:\Users\rennie\gitrepos> cd google-cloud-python
PS C:\Users\rennie\gitrepos\google-cloud-python> cd tasks
PS C:\Users\rennie\gitrepos\google-cloud-python\tasks> python -m synthtool
Traceback (most recent call last):
  File "C:\Users\rennie\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\rennie\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\rennie\AppData\Roaming\Python\Python37\site-packages\synthtool\__main__.py", line 24, in <module>
    import synthtool.metadata
  File "C:\Users\rennie\AppData\Roaming\Python\Python37\site-packages\synthtool\metadata.py", line 19, in <module>
    import google.protobuf.json_format
ModuleNotFoundError: No module named 'google.protobuf'
PS C:\Users\rennie\gitrepos\google-cloud-python\tasks> python -m pip install --user --upgrade gcp-synthtool
Requirement already up-to-date: gcp-synthtool in c:\users\rennie\appdata\roaming\python\python37\site-packages (2019.5.2)
Requirement not upgraded as not directly required: packaging in c:\users\rennie\appdata\roaming\python\python37\site-packages (from gcp-synthtool) (19.2)
Requirement not upgraded as not directly required: protobuf in c:\users\rennie\appdata\roaming\python\python37\site-packages (from gcp-synthtool) (3.10.0)
Requirement not upgraded as not directly required: colorlog in c:\users\rennie\appdata\roaming\python\python37\site-packages (from gcp-synthtool) (4.0.2)
Requirement not upgraded as not directly required: requests in c:\users\rennie\appdata\roaming\python\python37\site-packages (from gcp-synthtool) (2.22.0)
Requirement not upgraded as not directly required: PyYAML in c:\users\rennie\appdata\roaming\python\python37\site-packages (from gcp-synthtool) (5.1.2)
Requirement not upgraded as not directly required: click in c:\users\rennie\appdata\local\programs\python\python37\lib\site-packages (from gcp-synthtool) (7.0)
Requirement not upgraded as not directly required: jinja2 in c:\users\rennie\appdata\local\programs\python\python37\lib\site-packages (from gcp-synthtool) (2.10)
Requirement not upgraded as not directly required: pyparsing>=2.0.2 in c:\users\rennie\appdata\roaming\python\python37\site-packages (from packaging->gcp-synthtool) (2.4.2)
Requirement not upgraded as not directly required: six in c:\users\rennie\appdata\roaming\python\python37\site-packages (from packaging->gcp-synthtool) (1.12.0)
Requirement not upgraded as not directly required: setuptools in c:\users\rennie\appdata\local\programs\python\python37\lib\site-packages (from protobuf->gcp-synthtool) (39.0.1)
Requirement not upgraded as not directly required: colorama; sys_platform == "win32" in c:\users\rennie\appdata\roaming\python\python37\site-packages (from colorlog->gcp-synthtool) (0.4.1)
Requirement not upgraded as not directly required: certifi>=2017.4.17 in c:\users\rennie\appdata\roaming\python\python37\site-packages (from requests->gcp-synthtool) (2019.9.11)
Requirement not upgraded as not directly required: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\rennie\appdata\roaming\python\python37\site-packages (from requests->gcp-synthtool) (1.25.6)
Requirement not upgraded as not directly required: chardet<3.1.0,>=3.0.2 in c:\users\rennie\appdata\roaming\python\python37\site-packages (from requests->gcp-synthtool) (3.0.4)
Requirement not upgraded as not directly required: idna<2.9,>=2.5 in c:\users\rennie\appdata\roaming\python\python37\site-packages (from requests->gcp-synthtool) (2.8)
Requirement not upgraded as not directly required: MarkupSafe>=0.23 in c:\users\rennie\appdata\local\programs\python\python37\lib\site-packages (from jinja2->gcp-synthtool) (1.1.0)
You are using pip version 10.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\Users\rennie\gitrepos\google-cloud-python\tasks> python -m synthtool
Traceback (most recent call last):
  File "C:\Users\rennie\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\rennie\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\rennie\AppData\Roaming\Python\Python37\site-packages\synthtool\__main__.py", line 24, in <module>
    import synthtool.metadata
  File "C:\Users\rennie\AppData\Roaming\Python\Python37\site-packages\synthtool\metadata.py", line 19, in <module>
    import google.protobuf.json_format
ModuleNotFoundError: No module named 'google.protobuf'
PS C:\Users\rennie\gitrepos\google-cloud-python\tasks> python -m pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/30/db/9e38760b32e3e7f40cce46dd5fb107b8c73840df38f0046d8e6514e675a1/pip-19.2.3-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 3.2MB/s
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-19.2.3
PS C:\Users\rennie\gitrepos\google-cloud-python\tasks> python -m pip install --user --upgrade gcp-synthtool
Requirement already up-to-date: gcp-synthtool in c:\users\rennie\appdata\roaming\python\python37\site-packages (2019.5.2)
Requirement already satisfied, skipping upgrade: colorlog in c:\users\rennie\appdata\roaming\python\python37\site-packages (from gcp-synthtool) (4.0.2)
Requirement already satisfied, skipping upgrade: protobuf in c:\users\rennie\appdata\roaming\python\python37\site-packages (from gcp-synthtool) (3.10.0)
Requirement already satisfied, skipping upgrade: click in c:\users\rennie\appdata\local\programs\python\python37\lib\site-packages (from gcp-synthtool) (7.0)
Requirement already satisfied, skipping upgrade: jinja2 in c:\users\rennie\appdata\local\programs\python\python37\lib\site-packages (from gcp-synthtool) (2.10)
Requirement already satisfied, skipping upgrade: PyYAML in c:\users\rennie\appdata\roaming\python\python37\site-packages (from gcp-synthtool) (5.1.2)
Requirement already satisfied, skipping upgrade: packaging in c:\users\rennie\appdata\roaming\python\python37\site-packages (from gcp-synthtool) (19.2)
Requirement already satisfied, skipping upgrade: requests in c:\users\rennie\appdata\roaming\python\python37\site-packages (from gcp-synthtool) (2.22.0)
Requirement already satisfied, skipping upgrade: colorama; sys_platform == "win32" in c:\users\rennie\appdata\roaming\python\python37\site-packages (from colorlog->gcp-synthtool) (0.4.1)
Requirement already satisfied, skipping upgrade: six>=1.9 in c:\users\rennie\appdata\roaming\python\python37\site-packages (from protobuf->gcp-synthtool) (1.12.0)
Requirement already satisfied, skipping upgrade: setuptools in c:\users\rennie\appdata\local\programs\python\python37\lib\site-packages (from protobuf->gcp-synthtool) (39.0.1)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in c:\users\rennie\appdata\local\programs\python\python37\lib\site-packages (from jinja2->gcp-synthtool) (1.1.0)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in c:\users\rennie\appdata\roaming\python\python37\site-packages (from packaging->gcp-synthtool) (2.4.2)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\rennie\appdata\roaming\python\python37\site-packages (from requests->gcp-synthtool) (2019.9.11)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\rennie\appdata\roaming\python\python37\site-packages (from requests->gcp-synthtool) (1.25.6)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in c:\users\rennie\appdata\roaming\python\python37\site-packages (from requests->gcp-synthtool) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in c:\users\rennie\appdata\roaming\python\python37\site-packages (from requests->gcp-synthtool) (2.8)
PS C:\Users\rennie\gitrepos\google-cloud-python\tasks> which pip
/cygdrive/c/Users/rennie/AppData/Local/Programs/Python/Python37/Scripts/pip
PS C:\Users\rennie\gitrepos\google-cloud-python\tasks> which python
/cygdrive/c/Users/rennie/AppData/Local/Programs/Python/Python37/python
PS C:\Users\rennie\gitrepos\google-cloud-python\tasks> python -m synthtool
Traceback (most recent call last):
  File "C:\Users\rennie\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\rennie\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\rennie\AppData\Roaming\Python\Python37\site-packages\synthtool\__main__.py", line 24, in <module>
    import synthtool.metadata
  File "C:\Users\rennie\AppData\Roaming\Python\Python37\site-packages\synthtool\metadata.py", line 19, in <module>
    import google.protobuf.json_format
ModuleNotFoundError: No module named 'google.protobuf'
PS C:\Users\rennie\gitrepos\google-cloud-python\tasks> Stop-Transcript
**********************
Windows PowerShell transcript end
End time: 20191010155702
**********************
```

**Comment by SurferJeffAtGoogle** [comment]
Must have been a temporary issue?  I repeated the command today and it succeeded:
```ps1
PS C:\Users\rennie\gitrepos\synthtool> python -m pip install --user --upgrade gcp-synthtool
Requirement already up-to-date: gcp-synthtool in c:\users\rennie\gitrepos\synthtool (2019.10.17)
Collecting click (from gcp-synthtool)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any
.whl
Collecting colorlog (from gcp-synthtool)
  Using cached https://files.pythonhosted.org/packages/68/4d/892728b0c14547224f0ac40884e722a3d00cb54e7a146aea0b3186806c9e/colorlog-4.0.2-py2.py3-non
e-any.whl
Collecting jinja2 (from gcp-synthtool)
  Using cached https://files.pythonhosted.org/packages/65/e0/eb35e762802015cab1ccee04e8a277b03f1d8e53da3ec3106882ec42558b/Jinja2-2.10.3-py2.py3-none
-any.whl
Collecting packaging (from gcp-synthtool)
  Using cached https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-non
e-any.whl
Collecting PyYAML (from gcp-synthtool)
  Downloading https://files.pythonhosted.org/packages/21/5f/91ae0681bceb7ae183552b0364cfd21c9f173e2f2553229bb74968e31ea0/PyYAML-5.2-cp27-cp27m-win_a
md64.whl (210kB)
    100% |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 215kB 2.0MB/s
Collecting requests (from gcp-synthtool)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-no
ne-any.whl
Collecting protobuf (from gcp-synthtool)
  Downloading https://files.pythonhosted.org/packages/4e/26/1517e42a81de4f28ed0f3cdadb628c1b72f3a28f38323a05e251f5df0a29/protobuf-3.11.1-py2.py3-non
e-any.whl (434kB)
    100% |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 440kB 1.9MB/s
Collecting colorama; sys_platform == "win32" (from colorlog->gcp-synthtool)
  Using cached https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-non
e-any.whl
Collecting MarkupSafe>=0.23 (from jinja2->gcp-synthtool)
  Downloading https://files.pythonhosted.org/packages/f7/58/85258115ce58190f20c28fbb3b91c3b1a0a42e6375b100e489427c30488a/MarkupSafe-1.1.1-cp27-cp27m
-win_amd64.whl
Collecting pyparsing>=2.0.2 (from packaging->gcp-synthtool)
  Using cached https://files.pythonhosted.org/packages/c0/0c/fc2e007d9a992d997f04a80125b0f183da7fb554f1de701bbb70a8e7d479/pyparsing-2.4.5-py2.py3-no
ne-any.whl
Requirement already satisfied, skipping upgrade: six in c:\python_27_amd64\files\lib\site-packages (from packaging->gcp-synthtool) (1.11.0)
Collecting certifi>=2017.4.17 (from requests->gcp-synthtool)
  Using cached https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3
-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->gcp-synthtool)
  Using cached https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-non
e-any.whl
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in c:\python_27_amd64\files\lib\site-packages (from requests->gcp-synthtool) (2.7)
Collecting chardet<3.1.0,>=3.0.2 (from requests->gcp-synthtool)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none
-any.whl
Requirement already satisfied, skipping upgrade: setuptools in c:\python_27_amd64\files\lib\site-packages (from protobuf->gcp-synthtool) (39.0.1)
Installing collected packages: click, colorama, colorlog, MarkupSafe, jinja2, pyparsing, packaging, PyYAML, certifi, urllib3, chardet, requests, pro
tobuf
  The script chardetect.exe is installed in 'C:\Users\rennie\AppData\Roaming\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed MarkupSafe-1.1.1 PyYAML-5.2 certifi-2019.11.28 chardet-3.0.4 click-7.0 colorama-0.4.3 colorlog-4.0.2 jinja2-2.10.3 packaging-
19.2 protobuf-3.11.1 pyparsing-2.4.5 requests-2.22.0 urllib3-1.25.7
You are using pip version 18.0, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\Users\rennie\gitrepos\synthtool>
```
