### ISSUE TITLE
Autosynth failed - suspect latest synthtool changed

### ISSUE THREAD

**Issue by jskeet** [googleapis/synthtool#371]
Overnight all the autosynth tasks for C# failed, with a failure like this:

```text
Cloning into 'working_repo'...
Switched to branch 'autosynth-Google.Cloud.Asset.V1'
Traceback (most recent call last):
  File "/home/kbuilder/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kbuilder/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmpfs/src/git/autosynth/autosynth/synth.py", line 256, in <module>
    main()
  File "/tmpfs/src/git/autosynth/autosynth/synth.py", line 196, in main
    last_synth_commit_hash = get_last_metadata_commit(args.metadata_path)
  File "/tmpfs/src/git/autosynth/autosynth/synth.py", line 149, in get_last_metadata_commit
    text=True,
  File "/home/kbuilder/.pyenv/versions/3.6.1/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'
```

It was fine yesterday, so I *suspect* #369 is the cause here. (I haven't looked any further yet.)

Personally I believe we should absolutely use UTF-8 regardless of the locale-specific encoding, although I'd hope that UTF-8 would be the preferred encoding anyway.

**Comment by jskeet** [comment]
Looks like this was a separate change in Autosynth - although I still think it's best to explicitly use UTF-8.
