### ISSUE TITLE
document bazel dependency

### ISSUE THREAD

**Issue by elharo** [googleapis/synthtool#511]
elharo@elharo1:~/java-spanner$ python3 -m synthtool
2020-04-30 09:38:24,532 synthtool > Executing /home/elharo/java-spanner/synth.py.
On branch exp
nothing to commit, working tree clean
2020-04-30 09:38:24,608 synthtool > Ensuring dependencies.
2020-04-30 09:38:24,618 synthtool > Wrote metadata to synth.metadata.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/elharo/.local/lib/python3.6/site-packages/synthtool/__main__.py", line 102, in <module>
    main()
  File "/home/elharo/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/elharo/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/elharo/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/elharo/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/elharo/.local/lib/python3.6/site-packages/synthtool/__main__.py", line 94, in main
    spec.loader.exec_module(synth_module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/elharo/java-spanner/synth.py", line 23, in <module>
    gapic = gcp.GAPICBazel()
  File "/home/elharo/.local/lib/python3.6/site-packages/synthtool/gcp/gapic_bazel.py", line 42, in __init__
    self._ensure_dependencies_installed()
  File "/home/elharo/.local/lib/python3.6/site-packages/synthtool/gcp/gapic_bazel.py", line 301, in _ensure_dependencies_installed
    f"Dependencies missing: {', '.join(failed_dependencies)}"
OSError: Dependencies missing: bazel

**Comment by thebrianchen** [comment]
I ran into this error as well but installing bazel via homebrew resolved the issue for me.
