### ISSUE TITLE
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/googleapis/nodejs-rcloadenv/issues

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/synthtool#549]
I happened to notice that a nightly synthtool job isn't doing what I expected.  I went to http://fusion, and discovered this:
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod%3Acloud-devrel%2Fclient-libraries%2Fautosynth%2Fnodejs

The first failure I noticed looks like this:

```
2020-05-13 05:48:18,368 autosynth [INFO] > Synthesizing nodejs-bigquery-storage.
2020-05-13 05:48:18,368 autosynth [DEBUG] > Running: {' '.join(command)}
Traceback (most recent call last):
  File "/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmpfs/src/github/synthtool/autosynth/multi.py", line 231, in <module>
    main()
  File "/tmpfs/src/github/synthtool/autosynth/multi.py", line 222, in main
    report_to_github_issues(gh, results)
  File "/tmpfs/src/github/synthtool/autosynth/multi.py", line 190, in report_to_github_issues
    _file_or_comment_on_issue(gh, result, issue_title, existing_issue)
  File "/tmpfs/src/github/synthtool/autosynth/multi.py", line 153, in _file_or_comment_on_issue
    labels=labels,
  File "/tmpfs/src/github/synthtool/autosynth/github.py", line 143, in create_issue
    response.raise_for_status()
  File "/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/googleapis/nodejs-rcloadenv/issues


[ID: 6486594] Build finished after 6221 secs, exit value: 1
```

**Comment by bcoe** [comment]
a couple additional things jumped out at me digging into this issue:

1.  `subprocess.run` failed with a `0`, so wasn't breaking the build for code generation in `google-api-nodejs-client` (like it should have).
2. I'm not sure what the heck is going on with `nodejs-rcloadenv`, I believe I've seen this error if an attempt is made to open a PR with no changes, I wonder if we could add some more logging and catch this.

**Comment by SurferJeffAtGoogle** [comment]
The build status changes are already being sent to an internal team alias, which my inbox filters were sending directly to archive.  I've updated my filters to let these messages arrive.

**Comment by chingor13** [comment]
This is failing when trying to report a failure to GitHub. #548 should allow logging the actual error response from GitHub. #551 will allow the autosynth run to continue to report on other repositories (and make it report immediately after synthesizing the library).
