### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/synthtool#552]
This autosynth bug was filed:
https://github.com/googleapis/sloth/issues/678

With the stack trace:

```
2020-05-14 06:37:10,235 autosynth [INFO] > logs will be written to: /tmpfs/src/github/synthtool/logs/googleapis/sloth
2020-05-14 06:37:10,238 synthtool [ERROR] > Failed executing git clone --single-branch https://github.com/googleapis/sloth.git /home/kbuilder/.cache/synthtool/sloth:

fatal: could not create work tree dir '/home/kbuilder/.cache/synthtool/sloth': No space left on device

Traceback (most recent call last):
  File "/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmpfs/src/github/synthtool/autosynth/synth.py", line 600, in <module>
    main()
  File "/tmpfs/src/github/synthtool/autosynth/synth.py", line 472, in main
    return _inner_main(temp_dir)
  File "/tmpfs/src/github/synthtool/autosynth/synth.py", line 519, in _inner_main
    working_repo_path = synthtool_git.clone(f"https://github.com/{args.repository}.git")
  File "/tmpfs/src/github/synthtool/synthtool/sources/git.py", line 83, in clone
    shell.run(cmd, check=True)
  File "/tmpfs/src/github/synthtool/synthtool/shell.py", line 39, in run
    raise exc
  File "/tmpfs/src/github/synthtool/synthtool/shell.py", line 33, in run
    encoding="utf-8",
  File "/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'clone', '--single-branch', 'https://github.com/googleapis/sloth.git', PosixPath('/home/kbuilder/.cache/synthtool/sloth')]' returned non-zero exit status 128.
```

**Comment by skuruppu** [comment]
Same here in https://github.com/googleapis/nodejs-spanner/issues/960.

**Comment by SurferJeffAtGoogle** [comment]
Fixed by https://github.com/googleapis/synthtool/pull/558
