### ISSUE TITLE
Autosynth sometimes creates bugs with a body longer than github's limits.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/synthtool#553]
```
2020-05-14 04:01:46,694 autosynth [ERROR] > Error making request (422): Validation Failed
2020-05-14 04:01:46,694 autosynth [DEBUG] > {'message': 'Validation Failed', 'errors': [{'resource': 'Issue', 'code': 'custom', 'field': 'body', 'message': 'body is too long (maximum is 65536 characters)'}], 'documentation_url': 'https://developer.github.com/v3/issues/#create-an-issue'}
Traceback (most recent call last):
  File "/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmpfs/src/github/synthtool/autosynth/multi.py", line 235, in <module>
    main()
  File "/tmpfs/src/github/synthtool/autosynth/multi.py", line 226, in main
    report_to_github_issues(gh, results)
  File "/tmpfs/src/github/synthtool/autosynth/multi.py", line 194, in report_to_github_issues
    _file_or_comment_on_issue(gh, result, issue_title, existing_issue)
  File "/tmpfs/src/github/synthtool/autosynth/multi.py", line 157, in _file_or_comment_on_issue
    labels=labels,
  File "/tmpfs/src/github/synthtool/autosynth/github.py", line 215, in create_issue
    return cast(Dict, _get_json_or_raise_exception(response))
  File "/tmpfs/src/github/synthtool/autosynth/github.py", line 389, in _get_json_or_raise_exception
    response.raise_for_status()
  File "/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/googleapis/java-datacatalog/issues
```

Google developers can see the full log [here](https://fusion.corp.google.com/runanalysis/test/prod%3Acloud-devrel%2Fclient-libraries%2Fautosynth%2Fjava/prod%3Acloud-devrel%2Fclient-libraries%2Fautosynth%2Fjava/KOKORO/ca044f79-1029-4059-ba9d-ac1fc45df6f0/1589445022656/build%20%23742/Targets?target=cloud-devrel%2Fclient-libraries%2Fautosynth%2Fjava&drilldownTab=logs).

**Comment by SurferJeffAtGoogle** [comment]
Duplicate of https://github.com/googleapis/synthtool/issues/549
