### ISSUE TITLE
Autosynth jobs for node.js all failed

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/synthtool#605]
From what I can tell, it looks like every nodejs job failed last night:
https://g3c.corp.google.com/results/invocations/a84fe804-6b84-41a5-b1f2-e6d681e30fa2/targets/github%2Fsynthtool;config=default/tests

**Comment by JustinBeckwith** [comment]
@SurferJeffAtGoogle  - Unclear if this is a nodejs issue, or an autosynth issue - feel free to reassign once we know what's happenin

**Comment by SurferJeffAtGoogle** [comment]
49 failed, 39 passed.

For the 49 that failed, npm fix failed like this:
```
DEBUG:synthtool:Running fix...

> @google-cloud/asset@3.1.0 fix /usr/local/google/home/rennie/gitrepos/nodejs-asset
> gts fix

version: 8
Error: gts requires node.js 10.x or up. You are currently running
      v8.11.1, which is not supported. Please upgrade to
      a safe, secure version of nodejs!
    at run (/usr/local/google/home/rennie/gitrepos/nodejs-asset/node_modules/gts/build/src/cli.js:81:15)
    at Object.<anonymous> (/usr/local/google/home/rennie/gitrepos/nodejs-asset/node_modules/gts/build/src/cli.js:142:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

npm ERR! Linux 5.2.17-1rodete3-amd64
npm ERR! argv "/usr/local/google/home/rennie/Downloads/node-v4.2.1-linux-x64/bin/node" "/usr/local/google/home/rennie/Downloads/node-v4.2.1-linux-x64/bin/npm" "run" "fix"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! @google-cloud/asset@3.1.0 fix: `gts fix`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @google-cloud/asset@3.1.0 fix script 'gts fix'.
npm ERR! This is most likely a problem with the @google-cloud/asset package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gts fix
npm ERR! You can get their info via:
npm ERR!     npm owner ls @google-cloud/asset
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/google/home/rennie/gitrepos/nodejs-asset/npm-debug.log
2020-06-05 09:39:48,397 synthtool > Failed executing npm run fix:

None
ERROR:synthtool:Failed executing npm run fix:

None
```

**Comment by SurferJeffAtGoogle** [comment]
Actually, not 100% sure, but that's my most likely culprit right now.

**Comment by SurferJeffAtGoogle** [comment]
From the log:
```
Status: Downloaded newer image for gcr.io/gapic-images/gapic-generator-typescript:latest
2020-06-05 04:21:00,681 synthtool [DEBUG] > Generating code for: google/cloud/asset/v1beta1.
Traceback (most recent call last):
  File "/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmpfs/src/github/synthtool/synthtool/__main__.py", line 102, in <module>
    main()
  File "/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmpfs/src/github/synthtool/synthtool/__main__.py", line 94, in main
    spec.loader.exec_module(synth_module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kbuilder/.cache/synthtool/nodejs-asset/synth.py", line 42, in <module>
    version=version),
  File "/tmpfs/src/github/synthtool/synthtool/gcp/gapic_microgenerator.py", line 66, in typescript_library
    return self._generate_code(service, version, "typescript", **kwargs)
  File "/tmpfs/src/github/synthtool/synthtool/gcp/gapic_microgenerator.py", line 195, in _generate_code
    f"Code generation seemed to succeed, but {output_dir} is empty."
RuntimeError: Code generation seemed to succeed, but /tmpfs/tmp/tmp8q7p105x is empty.
2020-06-05 04:21:06,056 autosynth [ERROR] > Synthesis failed
```

**Comment by SurferJeffAtGoogle** [comment]
I kicked off another run and saw the exact same 49 failures and 39 successes:
https://fusion.corp.google.com/runanalysis/test/prod%3Acloud-devrel%2Fclient-libraries%2Fautosynth%2Fnodejs/prod%3Acloud-devrel%2Fclient-libraries%2Fautosynth%2Fnodejs/KOKORO/efbc612a-a1be-43b9-a32e-48ba98cdbde3/1591375912688/build%20%23744/Targets?target=github%2Fsynthtool&drilldownTab=tests

**Comment by SurferJeffAtGoogle** [comment]
Running synthtool manually:
```
> @google-cloud/asset@3.1.0 compile /usr/local/google/home/rennie/gitrepos/nodejs-asset
> tsc -p . && cp -r protos build/

node_modules/google-gax/build/protos/iam_service.d.ts:4291:40 - error TS2304: Cannot find name 'Long'.

4291             positiveIntValue?: (number|Long|null);
                                            ~~~~

node_modules/google-gax/build/protos/iam_service.d.ts:4294:40 - error TS2304: Cannot find name 'Long'.

4294             negativeIntValue?: (number|Long|null);
                                            ~~~~

node_modules/google-gax/build/protos/iam_service.d.ts:4322:46 - error TS2304: Cannot find name 'Long'.

4322             public positiveIntValue: (number|Long);
                                                  ~~~~

node_modules/google-gax/build/protos/iam_service.d.ts:4325:46 - error TS2304: Cannot find name 'Long'.

4325             public negativeIntValue: (number|Long);
                                                  ~~~~

node_modules/google-gax/build/protos/operations.d.ts:3762:40 - error TS2304: Cannot find name 'Long'.

3762             positiveIntValue?: (number|Long|null);
                                            ~~~~

node_modules/google-gax/build/protos/operations.d.ts:3765:40 - error TS2304: Cannot find name 'Long'.

3765             negativeIntValue?: (number|Long|null);
                                            ~~~~

node_modules/google-gax/build/protos/operations.d.ts:3793:46 - error TS2304: Cannot find name 'Long'.

3793             public positiveIntValue: (number|Long);
                                                  ~~~~

node_modules/google-gax/build/protos/operations.d.ts:3796:46 - error TS2304: Cannot find name 'Long'.

3796             public negativeIntValue: (number|Long);
                                                  ~~~~

node_modules/google-gax/build/protos/operations.d.ts:4485:31 - error TS2304: Cannot find name 'Long'.

4485             seconds?: (number|Long|null);
                                   ~~~~

node_modules/google-gax/build/protos/operations.d.ts:4501:37 - error TS2304: Cannot find name 'Long'.

4501             public seconds: (number|Long);
                                         ~~~~

protos/protos.d.ts:15:23 - error TS2307: Cannot find module 'long' or its corresponding type declarations.

15 import * as Long from "long";
                         ~~~~~~

protos/protos.d.ts:16:28 - error TS2307: Cannot find module 'protobufjs' or its corresponding type declarations.

16 import * as $protobuf from "protobufjs";
                              ~~~~~~~~~~~~


Found 12 errors.
```

**Comment by JustinBeckwith** [comment]
A group of us got together to debug this, and made some interesting discoveries!
- On my machine, `synthtool` fails with a different set of TypeScript compiler errors
- For @bcoe, @alexander-fenster, and @xiaozhenliu-gg5 `synthtool` "works on their machines" ™️ 
- I tried to update to the latest synthtool by running `python3 -m pip install --user --upgrade git+https://github.com/googleapis/synthtool.git`
- After debugging, we theorized that I was *not* running the latest synthtool
- `synthtool --version` appears to be stuck on a release from feb, so it's very hard for me to know what version I'm actually running related to others (a hash here may be appropriate, or auto-releasing synthtool automatically)
- I re-read the new instructions, cloned synthtool locally, and tried running `python3 -m pip install -e .`
- I tried running `synthtool` again from the `nodejs-asset` directory, and still got TypeScript errors
- We tried a method where I used virtualenv and pip to install synthtool, and that worked!

My guess - something with installation of synthtool seemed to change recently, and it's causing old versions to get installed.  `synthtool --version` is not useful, as we all use synthtool from head, and it just reports the same number back.

**Comment by SurferJeffAtGoogle** [comment]
With some recent recent changes to synthtool (thank you @chingor13 and @dazuma), we now see the full synthlog:

https://cnsviewer2.corp.google.com/placer/prod/home/kokoro-dedicated/build_artifacts/prod/cloud-devrel/client-libraries/autosynth/nodejs/745/20200605-151055/github/synthtool/logs/googleapis/nodejs-asset/self/2/sponge_log.log

Notably, I see this:
```
DEBUG:synthtool:Generating code for: google/cloud/asset/v1beta1.
gapic-generator-typescript: https://github.com/googleapis/gapic-generator-typescript
Latest commit: 
commit a858a371e225254fca1c32d8d6b142b42cb711ad
Author: release-please[bot] <55107282+release-please[bot]@users.noreply.github.com>
Date:   Thu Jun 4 16:54:54 2020 -0700

child_process.js:642
    throw err;
    ^

Error: spawnSync protoc EACCES
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:607:24)
    at Object.execFileSync (child_process.js:634:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/@google-cloud/gapic-generator/build/src/gapic-generator-typescript.js:117:17)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawnSync protoc',
  path: 'protoc',
  spawnargs: [
    '--plugin=protoc-gen-typescript_gapic=/usr/local/lib/node_modules/@google-cloud/gapic-generator/build/src/protoc-plugin.js',
    '--typescript_gapic_out=/out',
    '--gapic-validator_out=.',
    '--typescript_gapic_opt="grpc-service-config=google/cloud/asset/v1beta1/cloudasset_grpc_service_config.json"',
    '--typescript_gapic_opt="package-name=@google-cloud/asset"',
    '--experimental_allow_proto3_optional',
    '-I/in',
    '/in/google/cloud/orgpolicy/v1/orgpolicy.proto',
    '/in/google/cloud/asset/v1beta1/assets.proto',
    '/in/google/cloud/asset/v1beta1/asset_service.proto',
    '/in/google/cloud/common_resources.proto',
    '/in/google/identity/accesscontextmanager/v1/service_perimeter.proto',
    '/in/google/identity/accesscontextmanager/v1/access_level.proto',
    '/in/google/identity/accesscontextmanager/v1/access_policy.proto',
    '/in/google/identity/accesscontextmanager/type/device_resources.proto',
    '-I/protos/api-common-protos-master'
  ],
  error: [Circular],
  status: null,
  signal: null,
  output: null,
  pid: 17,
  stdout: null,
  stderr: null
}
```

Looks like an EACCESS error when nodejs tries to invoke the proto compiler.

**Comment by SurferJeffAtGoogle** [comment]
@alexander-fenster, can you try rolling back to an earlier version of the gapic generator?

**Comment by alexander-fenster** [comment]
@SurferJeffAtGoogle Thank you, that finally starts making sense! Do you log the complete `docker run` command, and also, what user (UID) is running that command if possible?

**Comment by alexander-fenster** [comment]
(re: roll back, I can do it, but before I do, I just wanted to check something here)

**Comment by chingor13** [comment]
Docker invocation: https://github.com/googleapis/synthtool/blob/9c2913e1831eb00fa01317f3fea4ce25d3f657eb/synthtool/gcp/gapic_microgenerator.py#L150-L160

**Comment by alexander-fenster** [comment]
Yep. This is it! Thank you for investigation.

`protoc` release 3.11.2 (previously used): in https://github.com/protocolbuffers/protobuf/releases/download/v3.11.2/protoc-3.11.2-linux-x86_64.zip, `bin/protoc` has permissions set to 755 (`-rwxr-xr-x`)

`protoc` release 3.12.3 (currently used): in https://github.com/protocolbuffers/protobuf/releases/download/v3.12.3/protoc-3.12.3-linux-x86_64.zip, `bin/protoc` has permissions set to 750 (`-rwxr-x---`)

Since you folks use `--user`option for `docker run`, it runs as non-root user and cannot execute `protoc`. Fixing now by adding extra`chmod` in the generator's `Dockerfile`.
