### ISSUE TITLE
Autosynth failing for googleapis/google-resumable-media-python

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/synthtool#754]
There is an autosynth failure here that's interesting:
https://github.com/googleapis/google-resumable-media-python/issues/167

It looks like autosynth is failing to submit a PR for some reason?

```
2020-09-10 05:17:33,249 autosynth [DEBUG] > Running: git log -1 --pretty=%b
2020-09-10 05:17:33,695 autosynth [ERROR] > Error making request (422): Validation Failed
2020-09-10 05:17:33,695 autosynth [DEBUG] > {'message': 'Validation Failed', 'errors': [{'resource': 'PullRequest', 'code': 'custom', 'message': 'A pull request already exists for googleapis:autosynth.'}], 'documentation_url': 'https://docs.github.com/rest/reference/pulls#create-a-pull-request'}
2020-09-10 05:17:33,696 autosynth [DEBUG] > Running: git clean -fdx
Removing __pycache__/
Removing google/__pycache__/
Traceback (most recent call last):
  File "/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmpfs/src/github/synthtool/autosynth/synth.py", line 690, in <module>
    main()
  File "/tmpfs/src/github/synthtool/autosynth/synth.py", line 539, in main
    return _inner_main(temp_dir)
  File "/tmpfs/src/github/synthtool/autosynth/synth.py", line 670, in _inner_main
    commit_count = synthesize_loop(x, multiple_prs, change_pusher, synthesizer)
  File "/tmpfs/src/github/synthtool/autosynth/synth.py", line 388, in synthesize_loop
    pr = change_pusher.push_changes(1, toolbox.branch, pr_title)
  File "/tmpfs/src/github/synthtool/autosynth/change_pusher.py", line 103, in push_changes
    self._repository, branch=branch, title=pr_title, body=new_body,
  File "/tmpfs/src/github/synthtool/autosynth/github.py", line 94, in create_pull_request
    return cast(Dict, _get_json_or_raise_exception(response))
  File "/tmpfs/src/github/synthtool/autosynth/github.py", line 488, in _get_json_or_raise_exception
    response.raise_for_status()
  File "/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/googleapis/google-resumable-media-python/pulls
```

**Comment by SurferJeffAtGoogle** [comment]
It's failing because there is an existing "chore: start tracking obsolete files" pull request, and it's trying to create another one.  I'll add code to detect this case.
