### ISSUE TITLE
Synth failing during ensuring dependencies

### ISSUE THREAD

**Issue by TheRoyalTnetennba** [googleapis/synthtool#89]
Running on Mac. asdf is managing python version (3.6.6). Tried rebooting and deleting cache. 
Any insight would be greatly appreciated.

```synthtool > Ensuring dependencies.
synthtool > Failed executing /Users/paye/.cache/synthtool/artman_venv/bin/pip install --upgrade googleapis-artman:

Collecting googleapis-artman
  Using cached https://files.pythonhosted.org/packages/8c/18/d58e5ceb61f4f24ed883d94ae88d1e8e151ca2998790c594bacbf68e4df0/googleapis-artman-0.15.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/v4/l0qwz2tx6pb3tj97c8pjmtph00hyhq/T/pip-install-589ui9sp/googleapis-artman/setup.py", line 29, in <module>
        with io.open(os.path.join(cur_dir, 'Dockerfile')) as dockerfile:
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/v4/l0qwz2tx6pb3tj97c8pjmtph00hyhq/T/pip-install-589ui9sp/googleapis-artman/Dockerfile'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/v4/l0qwz2tx6pb3tj97c8pjmtph00hyhq/T/pip-install-589ui9sp/googleapis-artman/
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Traceback (most recent call last):
  File "synth.py", line 26, in <module>
    gapic = gcp.GAPICGenerator()
  File "/Users/paye/.local/lib/python3.6/site-packages/synthtool/gcp/gapic_generator.py", line 90, in __init__
    self._install_artman()
  File "/Users/paye/.local/lib/python3.6/site-packages/synthtool/gcp/gapic_generator.py", line 220, in _install_artman
    f"googleapis-artman{version_specifier}",
  File "/Users/paye/.local/lib/python3.6/site-packages/synthtool/shell.py", line 34, in run
    raise exc
  File "/Users/paye/.local/lib/python3.6/site-packages/synthtool/shell.py", line 28, in run
    encoding="utf-8",
  File "/Users/paye/.asdf/installs/python/3.6.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '[PosixPath('/Users/paye/.cache/synthtool/artman_venv/bin/pip'), 'install', '--upgrade', 'googleapis-artman']' returned non-zero exit status 1.
synthtool > Cleaned up 0 temporary directories.```

**Comment by theacodes** [comment]
Looks like a bad release of artman.

**Comment by theacodes** [comment]
PR for upstream fix: https://github.com/googleapis/artman/pull/509

Closing this for now.
