### ISSUE TITLE
Roughly 20% of nodejs synths failed last night with Error: Flag keys may not contain '-': dry-run

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/synthtool#898]
Example:
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:cloud-devrel%2Fclient-libraries%2Fautosynth%2Fnodejs-shard4
![image](https://user-images.githubusercontent.com/11778530/103916217-0358e600-50c1-11eb-9540-a782f6e2a629.png)

```
> @google-cloud/dns@2.1.0 prepare /home/kbuilder/.cache/synthtool/nodejs-dns
> npm run compile


> @google-cloud/dns@2.1.0 precompile /home/kbuilder/.cache/synthtool/nodejs-dns
> gts clean

/home/kbuilder/.cache/synthtool/nodejs-dns/node_modules/meow/index.js:61
		throw new Error(`Flag keys may not contain '-': ${invalidFlags.join(', ')}`);
		^

Error: Flag keys may not contain '-': dry-run
    at validateOptions (/home/kbuilder/.cache/synthtool/nodejs-dns/node_modules/meow/index.js:61:9)
    at meow (/home/kbuilder/.cache/synthtool/nodejs-dns/node_modules/meow/index.js:136:2)
    at Object.<anonymous> (/home/kbuilder/.cache/synthtool/nodejs-dns/node_modules/gts/build/src/cli.js:30:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @google-cloud/dns@2.1.0 precompile: `gts clean`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @google-cloud/dns@2.1.0 precompile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kbuilder/.npm/_logs/2021-01-07T11_01_49_314Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @google-cloud/dns@2.1.0 prepare: `npm run compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @google-cloud/dns@2.1.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kbuilder/.npm/_logs/2021-01-07T11_01_49_377Z-debug.log
```

**Comment by bcoe** [comment]
This looks like it case caused by [this](https://github.com/sindresorhus/meow/pull/168/files).

Which was in turn pulled in to `gts`, will dig into it tomorrow.

**Comment by bcoe** [comment]
This appears to have been corrected but this PR was left open.
