### ISSUE TITLE
"Running: git clean -fdx" fails for about 50% of Java autosynths beginning 2020-01-11

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/synthtool#901]
Started happening last night.
https://fusion.corp.google.com/runanalysis/test/prod:cloud-devrel%2Fclient-libraries%2Fautosynth%2Fjava-shard6/prod:cloud-devrel%2Fclient-libraries%2Fautosynth%2Fjava-shard6/KOKORO/d92db98b-28c2-49ea-a4ba-b3aa386105f3/1610358847841/build%20%23273/Targets?target=logs%2Fjava-phishingprotection&drilldownTab=logs

![image](https://user-images.githubusercontent.com/11778530/104206308-357d8700-53e4-11eb-9a35-0d1e9209c37a.png)

```
...
Source-Author: Google APIs <noreply@google.com>
Source-Date: Sat Jan 9 14:01:49 2021 -0800
Source-Repo: googleapis/googleapis
Source-Sha: 91e206bcfeaf8948ea03fe3cb1b7616108496cd3
Source-Link: https://github.com/googleapis/googleapis/commit/91e206bcfeaf8948ea03fe3cb1b7616108496cd3
[autosynth 49d5fa3] chore: update gapic-generator-java to 0.0.18
 6 files changed, 14 insertions(+), 7 deletions(-)
2021-01-11 02:29:27,321 autosynth [DEBUG] > Running: git log -1 --no-decorate --format=%B
2021-01-11 02:29:27,325 autosynth [DEBUG] > Running: git push --force origin autosynth
remote: 
remote: Create a pull request for 'autosynth' on GitHub by visiting:        
remote:      https://github.com/googleapis/java-phishingprotection/pull/new/autosynth        
remote: 
To https://github.com/googleapis/java-phishingprotection.git
 * [new branch]      autosynth -> autosynth
2021-01-11 02:29:31,000 autosynth [DEBUG] > Running: git log -1 --pretty=%b
2021-01-11 02:29:33,123 autosynth [DEBUG] > Running: git clean -fdx
Removing __pycache__/
Traceback (most recent call last):
  File "/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmpfs/src/github/synthtool/autosynth/synth.py", line 354, in <module>
    main()
  File "/tmpfs/src/github/synthtool/autosynth/synth.py", line 189, in main
    return _inner_main(temp_dir)
  File "/tmpfs/src/github/synthtool/autosynth/synth.py", line 334, in _inner_main
    commit_count = synthesize_loop(x, multiple_prs, change_pusher, synthesizer)
  File "/tmpfs/src/github/synthtool/autosynth/synth.py", line 92, in synthesize_loop
    synthesize_inner_loop(fork, synthesizer)
  File "/tmpfs/src/github/synthtool/autosynth/synth.py", line 137, in synthesize_inner_loop
    synthesizer, len(toolbox.versions) - 1
  File "/tmpfs/src/github/synthtool/autosynth/synth_toolbox.py", line 259, in synthesize_version_in_new_branch
    synthesizer.synthesize(synth_log_path, self.environ)
  File "/tmpfs/src/github/synthtool/autosynth/synthesizer.py", line 120, in synthesize
    synth_proc.check_returncode()  # Raise an exception.
  File "/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 389, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '['/tmpfs/src/github/synthtool/env/bin/python3', '-m', 'synthtool', '--metadata', 'synth.metadata', 'synth.py', '--']' returned non-zero exit status 1.
```

**Comment by chingor13** [comment]
Not sure what happened here. These all succeeded the next run and closed out
